### ISSUE TITLE
Unsearchable fields error doesn't list fields

### ISSUE THREAD

**Issue by mauricio-morales** [piplcom/piplapis-csharp#2]
In https://github.com/piplcom/piplapis-csharp/blob/master/Piplapis/Search/SearchAPIRequest.cs#L216
The error prints the Linq expression instead of the actual values:
`Some fields are unsearchable: System.Linq.Enumerable+WhereEnumerableIterator`1[Pipl.APIs.Data.Fields.Field]`

**Comment by joshliberty** [comment]
Fixed on master. New version (4.0.0.3) published on Nuget.
