### ISSUE TITLE
Country code is not allowing any value but 1

### ISSUE THREAD

**Issue by artiebob** [piplcom/piplapis-csharp#3]
When trying to search for any phone number with a country code outside of Canada/US it throws an exception. I am looking for phone numbers in Mexico. Country Code = 52. I did not see any documentation that indicated it was limited to Canada/US. 

Here is the offending code in Phone.cs

        [JsonIgnore]
        public override bool IsSearchable
        {
            get
            {
                return (!string.IsNullOrEmpty(Raw)) || 
                       (Number != null && (CountryCode == null || CountryCode == 0 || CountryCode == 1));
            }
        }

**Comment by roy-pipl** [comment]
Thanks so much for reaching out Mat and highlighting this code snippet. You're welcome to use the raw phone as well, just be sure to include a + prefix to let the system know you're searching internationally. (e.g. +52 xx xxx)
